### PR TITLE
Add Brazilian Portuguese Translation

### PR DESCRIPTION
**Pull request by Djanilson**

### CODE REVIEW

**Comment by johannesjo** [comment]
Good idea. This seems to be (almost) all English. I will provide a Google translated default.

**Comment by Djanilson** [comment]
Hi, @johannesjo the job is done! 

I liked the project it seems to be very interesting! (lots of integrations)

**Comment by johannesjo** [comment]
Thank you very much!

**Comment by johannesjo** [comment]
@gcoro I held a little hacktoberfest competition: https://dev.to/johannesjo/i-am-giving-away-50-bucks-for-your-hacktoberfest-contribution-472p
You're one of the two winners providing the most useful contribution in this years October. I am splitting it up, because both of you provided a complete set of translations and it doesn't seem fair to favor one over the other. Please get in touch with me to, so I can send the prize to you.

**Pull request merged**
