### PR TITLE
Gitlab integration

### PR DESCRIPTION
**Pull request by MostafaAmin07**
Well, this is the basic functionality for the Gitlab. It should be doing everything that Github is currently doing.

I have to say that the new structure is a lot easier than the previous one.
You did a great job @johannesjo.

But I think there is a problem not only with this but with Github as well and maybe the Jira integration.
The requests to the API are being sent too many times.

I have no experience with PWA so I don't know exactly what is happening and why the caching is not working correctly.

### CODE REVIEW

**Comment by MostafaAmin07** [comment]
That's what I found when I open the network tab.
too many requests

Also, I am so sorry for the blackout from my side I needed to take some time as a break. I tried to isolate myself and I didn't check my email so sorry for that.

**Comment by johannesjo** [comment]
This is truly amazing. Thanks a lot. 

Not sure I understand the caching issue.
I added a manual caching mechanism, but decided not to use it to keep complexity lower for now. Standard browser caching seems to work as it should however:
Screenshot from 2020-03-23 16-50-35

On another subject: I was wondering if I could interest you into becoming a "collaborator" for super productivity. This would mean that you would gain direct access to the repository and the ability to merge pull requests etc. 
You wouldn't have to do much at this point, but I would like for another person being able to step in, in case I am unavailable to continue working on this for whatever reason. Considering the outstanding work you have done so far for this project, it would be really great to have you on board!

**Comment by MostafaAmin07** [comment]
I am glad that I can be of help to you.

@johannesjo 
You already have my interest in this amazing project. I would love to keep on working on this for as long as I could.

**Comment by johannesjo** [comment]
That's wonderful news! I send you an invitation.

**Comment by johannesjo** [comment]
Btw.: if you intend to make further adjustments, please let me know upfront, so I can update you on the current situation. There are a lot of fundamental changes currently taking place in this branch: https://github.com/johannesjo/super-productivity/tree/feat/shared-task-list-via-tags

**Comment by MostafaAmin07** [comment]
Great, if I started working on anything new I will keep you updated.
And if you want me to do or help you with anything just tell me about it and I will try my best.

**Comment by MostafaAmin07** [comment]
I don't know why this is the case with me but the caching is not working for me.

api2 (2)
Can you give me a hint on how can I trace this? I looked into the local storage and I found a key value pair with key "SUP_GITHUB_ISSUE_CACHE_projectid" so the caching takes place.
But for some reason, it can't see it!!

**Comment by johannesjo** [comment]
Caching won't with for non 200 status codes. In the screenshot you posted there are a lot of 403s. Maybe it's a good idea to investigate those first.

`SUP_GITHUB_ISSUE_CACHE_projectid` is legacy stuff I didn't bother to clean up :) caching now completely relies on the browser to make smart decisions based on the Backends config. I want to add offline support again (via the service worker), but that's something for later.

**Comment by MostafaAmin07** [comment]
Well, the caching worked for Github but not with Gitlab and I think I know the problem now.
I will work on solving this right away.

**Comment by MostafaAmin07** [comment]
Never mind It all works in the latest master.

**Pull request merged**
