### PR TITLE
Added a new icon for macOS

### PR DESCRIPTION
**Pull request by solarlime**
# Description

Added a more appropriate icon file for macOS. I checked on my Mac; building and installing are correct.

## Issues Resolved

[This one](https://github.com/johannesjo/super-productivity/issues/3033)

### CODE REVIEW

**Comment by johannesjo** [comment]
Thank you very much! Looks great! Current icns is 512x512px. So probably we should stick to this?

**Comment by solarlime** [comment]
You don't need to fit this icns everywhere, as I think. It has icons from 16x16 for non-Retina displays to 512x512@2x for Retina displays (1024x1024). I personally don't have Windows or Linux installed, so I cannot check if it looks good there too. Maybe the existing one is a better choice for other systems. But you can check if you can; here is .svg:

**Comment by johannesjo** [comment]
The icns in the PR is only 256x256. This might be to small?

**Comment by solarlime** [comment]
> The icns in the PR you provided is only 256x256. This might be to small?

I'll check it out

**Comment by solarlime** [comment]
Checked, found nothing criminal. However, I recreated icns file in a different way.

**Comment by johannesjo** [comment]
Thank you for the update and also the universal build suggestion! Will check it out next week :)

**Pull request merged**
