### PR TITLE
Added italian locale

### PR DESCRIPTION
**Pull request by gcoro**

### CODE REVIEW

**Comment by gcoro** [comment]
I just noticed another user added this yesterday. I'm very sorry about the double pr about same feature, when I started there wasn't any
 
However I'll still keep this, as my translation is done by hand and not using any online translator, resulting more accurate...

**Comment by johannesjo** [comment]
I take your word for it, as my italian is quite rudimentary :) Mille grazie! Molto gentile!

**Comment by johannesjo** [comment]
@gcoro I held a little hacktoberfest competition: https://dev.to/johannesjo/i-am-giving-away-50-bucks-for-your-hacktoberfest-contribution-472p
You're one of the two winners providing the most useful contribution in this years October. I am splitting it up, because both of you provided a complete set of translations and it doesn't seem fair to favor one over the other. Please get in touch with me to, so I can send the prize to you.

**Comment by gcoro** [comment]
Wow, thank you!! :) I wasn't aware of it.
Where do I contact you?

**Comment by johannesjo** [comment]
I would need a paypal email address (hopefully you got one), so I can send you the money there.

**Comment by gcoro** [comment]
I have one :) giulia994@ymail.com

**Comment by gcoro** [comment]
Received them, thank you again!

**Pull request merged**
