### PR TITLE
update strings from en to zhtw

### PR DESCRIPTION
**Pull request by 5idereal**

### CODE REVIEW

**Comment by johannesjo** [comment]
Thank you! Please let me know, once this is ready to be reviewed!

**Comment by SiderealArt** [comment]
@johannesjo Hi! Sorry for the delay, this PR is ready for review!

**Comment by SiderealArt** [comment]
@johannesjo Hi! Could you maybe review this PR? Thanks!

**Comment by johannesjo** [comment]
Hi there! No worries. Something seems to be wrong unfortunately. Could you maybe try to merge the master branch again?

**Pull request closed without merging**
