### PR TITLE
GitHub private repos

### PR DESCRIPTION
**Pull request by MostafaAmin07**
Allow access to private github repos.

This should be done.

### CODE REVIEW

**Comment by johannesjo** [comment]
I find the formatting a little bit weird, but I fix this later on. Great work again! Wouldn't have guessed that it is this straightforward to implement. Thank you very much!

**Comment by MostafaAmin07** [comment]
Yeah sorry about that, I forgot to reformate the parts where I added the header.

**Comment by johannesjo** [comment]
No worries :)

**Comment by MostafaAmin07** [comment]
@johannesjo Thank you for this great application.

**Pull request merged**
