### PR TITLE
Documentation for Personal Access Token permission requirements

### LINKED ISSUE #3190: Gitlab Integration - Personal Access Token permission requirements
As referenced in this thread: https://github.com/johannesjo/super-productivity/discussions/2714#discussioncomment-9490660

There's currently no documentation or guidance in the UI for what the minimum Access Token permissions required are for the Gitlab integration.

It's good security practice to restrict permissions on these access tokens, even for local applications, in order to mitigate any damage that could be done if they were ever leaked.

Could these permissions be determined, and added to documentation? I'd also suggest displaying these in the config UI in a future release.

Screenshot of available permissions on Gitlab.com:
image

### PR DESCRIPTION
**Pull request by BanditsBacon**
# Description

Add Documention for Gitlab Integration - Personal Access Token permission requirements

## Issues Resolved
#3190

### CODE REVIEW

**Comment by johannesjo** [comment]
Thank you so much! This is really great! <3

**Comment by johannesjo** [comment]
The images don't seem to work for some reason... Does editing the doc from the github interface maybe help? 
https://github.com/johannesjo/super-productivity/blob/master/docs/github-access-token-instructions.md

**Comment by BanditsBacon** [comment]
ok i take a look later

**Comment by BanditsBacon** [comment]
Add a new PullRequest with the now, hoping, working images.

**Pull request merged**
