### PR TITLE
feat: #1221 toggle button for isAddToBottom

### PR DESCRIPTION
**Pull request by gotjoshua**
- [x] toggle button
- [x] logical behavior after redux

### CODE REVIEW

**Comment by gotjoshua** [comment]
as i am coding in gitpod, the linting setup leaves a bit to be desired...
might need some help with that before you merge it

**Comment by johannesjo** [comment]
Works nicely! Thank you very much. Could you have a look at the suggested adjustments?

**Review by johannesjo — APPROVED** [review]

**Comment by johannesjo** [comment]
@gotjoshua ping

**Review by gotjoshua — COMMENTED** [review]
> @gotjoshua ping

hey, sorry if i'm holding up the show... i thought i made it clear that I'm on vacation, and that you should feel free to adapt and merge as you see fit!!

**Comment by gotjoshua** [comment]
i resolved everything and you have a full go ahead from my side...
anything else needed?

**Comment by johannesjo** [comment]
Thank you! I'll try to make the adjustments to the e2e this friday.

**Comment by johannesjo** [comment]
Thanks again. This is merged now. I took the liberty to adjust the icon to make it consistent with the other one.

**Pull request merged**
