### PR TITLE
feat: RTL support

### PR DESCRIPTION
**Pull request by MostafaAmin07**
This is not done yet. I created it for style and code related discussions and reviews.
Will implement #158 when it's done.

### CODE REVIEW

**Comment by MostafaAmin07** [comment]
This is what I got with the first attempt at it.

Here you can see that there are still some problems with the styling of the main-headerو the add-task-bar component (also I think the add-task-bar looks good) and other components that still need to be fixed.
main
metrics
project settings

**Comment by johannesjo** [comment]
Wow! Thank you very much! That's great! Do you need help with the header? Does it maybe make sense to move the action-nav (the buttons including the big play button) to the very left?

**Comment by MostafaAmin07** [comment]
Sorry for the late reply.
I managed to solve the issue with the main header and the banner.
fix

What I will do in the upcoming week is to try and go through all the scenarios I can find to make sure that the styling looks right, reserving the original style of the application.

**Comment by johannesjo** [comment]
Thank you! Looks very good so far. Let me know when you're done or if you have any questions!

**Comment by MostafaAmin07** [comment]
@johannesjo I think I am done here.
I have covered a lot of the possible scenarios in the application so far. I fixed what I thought is wrong with the design and I can't find any more apparent design flaws for the RTL.
I can't be 100% sure though that I covered all.
Anyway, I would love to help with any problem regarding the RTL design in the future.

I found a bug while working on this issue and I will create a separate issue for it with all the needed details. I will need your help with this one.

**Comment by johannesjo** [comment]
That's really amazing. Thank you very much! I'll check the code as soon as I get home.

**Comment by johannesjo** [comment]
Seems to work great and as far as i can see there are no issues with the ltr version neither. I made one minor comment, otherwise we're good to merge.

**Comment by MostafaAmin07** [comment]
Sorry, where is that comment that you made I can't find it?

**Comment by johannesjo** [comment]
@MostafaAmin07 
I made a comment regarding this line in the app.compontent.ts.
``` 
<ng-container *ngIf="(isAllDataLoadedInitially$|async)" [dir]="isRTL ? 'rtl' : 'ltr'">
```
This (`[dir]="isRTL ? 'rtl' : 'ltr'"`) doesn't seem to do anything or am I overlooking anything?

**Comment by MostafaAmin07** [comment]
Angular doesn't expect the dir attribute on the html tag to be changed. So the direction of the displayed elements doesn't get updated correctly.

The solution to this problem is wrapping all the components inside the app component inside a div or in this case, it was the ng-container then changing the dir attribute on that tag.
That way all the elements inside will get updated correctly.

**Comment by MostafaAmin07** [comment]
rtl
This is how it would look like without that line.

**Comment by johannesjo** [comment]
Alright. I am just really confused, because it doesn't seem to change anything in the dom (except for a comment node).

**Pull request merged**
