### PR TITLE
feat: Add Today Remaining in the projects view

### PR DESCRIPTION
**Pull request by shafiahmed12**
# Description
Filtering the tasks present in the projects and passing it to the mapEstimateRemainingFromTasks method so that the remaining time is calculated only for the tasks that are added to today
Describe what this change achieves

## Issues Resolved
https://github.com/johannesjo/super-productivity/issues/3221

## How it looks with this fix
image
image

#### Nothing is shown on Today page
image

## Check List

- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Comment by johannesjo** [comment]
Thank you very much! I've to say that – while certainly  useful – it feels a bit cluttered with 4 entries and also the display logic of when to display icons instead does not work well with 4 entries. Maybe it is better to just show this info on hover using matTooltip? What do you think?

**Comment by shafiahmed12** [comment]
> Thank you very much! I've to say that – while certainly useful – it feels a bit cluttered with 4 entries and also the display logic of when to display icons instead does not work well with 4 entries. Maybe it is better to just show this info on hover using matTooltip? What do you think?

I think that is a good idea, do you want this on hover on estimate remaining?

**Comment by johannesjo** [comment]
Yes and yes :) thank you!

**Comment by shafiahmed12** [comment]
> Yes and yes :) thank you!

made the changes as requested hope you are okay with this one :)

**Comment by johannesjo** [comment]
Thank you very much! I like it a lot! :)

**Comment by shafiahmed12** [comment]
> Thank you very much! I like it a lot! :)

This was my very first contribution and thanks for the confidence boost ✌

**Pull request merged**
