### PR TITLE
feat(issues): Add ability to filter caldav issues by category.

### PR DESCRIPTION
**Pull request by janLo**
# Description

This adds the possibility to filter caldav issues by category

## Issues Resolved

None

## Check List

- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Comment by janLo** [comment]
I found unexpectedly 10 minutes today to work on this and add a missing feature: I have one calendar for multiple projects and distinguish the tasks  by category. Now I want o have this separation mapped on different SP-Projects. This change implements this as a simple and optional filter for issue-search and backlog-pull.

Do I have to increment the MODEL_VERSION again?

**Comment by johannesjo** [comment]
Something went wrong with the e2e tests. Maybe you just need to merge or rebase the master branch again?

**Comment by janLo** [comment]
I thought I'd rebased before I started. I'll have a look asap.

**Comment by janLo** [comment]
@johannesjo do I need to increment the model version again?

**Comment by johannesjo** [comment]
@janLo nope. Should not be necessary-

**Comment by janLo** [comment]
I don't understand what is failing there: https://github.com/johannesjo/super-productivity/pull/918/checks?check_run_id=1947243663#step:7:229

**Comment by janLo** [comment]
@johannesjo I get the same error locally on the current master

**Comment by johannesjo** [comment]
> @johannesjo I get the same error locally on the current master

The unit testing error should be fixed (was only there on master for a couple of minutes, but you seem to have catched it :D). If I remember correctly we had an e2e testing error before?

**Comment by janLo** [comment]
I think so, yes. I've rebased again.

**Comment by janLo** [comment]
Seems to be alright now :)

**Comment by johannesjo** [comment]
Thank you once more @janLo ! Keep 'em coming !! <3

**Pull request merged**
