### PR TITLE
Gitlab fix and optimization

### LINKED ISSUE #562: Gitlab: Is not properly configured => implement bulk update check
Looking at the console errors I believe this to be an issue with hitting the GitLab API too frequently. [HTTP Status Code 429 Too Many Requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429).

On a side note, I think the error message needs updating for this type of error too. I would say that GitLab is configured correctly as I can see GitLab issues. This error is more related to api rate limiting.

### Your Environment

* Version used: 5.9.9 Microsoft Store
* Operating System and version: W10 2004 (build 19041.508)

### Expected Behavior

Update the GitLab issues without errors

### Current Behavior

Pop-up repeatedly appears at bottom of app saying `Gitlab: Is not properly configured`.

### Steps to Reproduce (for bugs)

1. Setup 3 projects with GitLab integration
1. Go to each project and add some tasks (from GitLab and just in super productivity)
1. Keep flipping between projects adding tasks until the `Gitlab: Is not properly configured` error repeatedly appears

### Console Output

```
GLOBAL_ERROR_HANDLER Error: Uncaught (in promise): Object: {"HANDLED_ERROR_PROP":"Gitlab: Http failure response for https://gitlab.com/api/v4/projects/organization%2Fgroup%2Fproject/issues?order_by=updated_at&per_page=100&page=1: 429 OK"}
    at S (polyfills.aebe8ecc43d658291381.js:1)
    at polyfills.aebe8ecc43d658291381.js:1
    at s (main.5a62f0f816872b3b2a47.js:1)
    at t.invoke (polyfills.aebe8ecc43d658291381.js:1)
    at Object.onInvoke (main.5a62f0f816872b3b2a47.js:1)
    at t.invoke (polyfills.aebe8ecc43d658291381.js:1)
    at e.run (polyfills.aebe8ecc43d658291381.js:1)
    at polyfills.aebe8ecc43d658291381.js:1
    at t.invokeTask (polyfills.aebe8ecc43d658291381.js:1)
    at Object.onInvokeTask (main.5a62f0f816872b3b2a47.js:1)
t.handleError @ main.5a62f0f816872b3b2a47.js:1
```

### Error Log (Desktop only)

Can't do this, the `%USERPROFILE%\AppData\Roaming\superProductivity` folder does not exist...

### LINKED ISSUE #564: What are "unresolved issues" in the GitLab integration?
What exactly is an "unresolved issues" in the GitLab integration setting "Automatically add unresolved issues from Gitlab to backlog"? I would expect that to be all open issues with a tag (I don't want issues just sat in the open column i.e. the backlog to be in Super Productivity). Instead I am getting issues that have been closed. Interestingly, for 2 out of 3 projects it imports all issues (closed and opened). For the other project it only imported 61 out of 158 issues (maybe it had hit a rate limit and didn't download the rest?).

Not sure if this is a bug or feature request so will let you categorize =)

### Your Environment
* Version used: 5.9.9 Microsoft Store
* Operating System and version: W10 2004 (build 19041.508)

### Expected Behavior
Closed GitLab issues **aren't** imported into Super Productivity

### Current Behavior
Closed GitLab issues **are** imported into Super Productivity

### PR DESCRIPTION
**Pull request by MostafaAmin07**
# Description

Fixed importing of all issues to only import opened issues.
Improved search for issues as now it uses the GitLab API search endpoint thus making fewer requests.
Fixed the refresh issues behavior to only send requests for the existing ones.

I was trying to introduce a way to handle the rate limit for Gitlab API based on the response headers but, it can't be accessed through the response object. So I am still searching for a good way to account for the rate limit.

Also, I am working on making the requests to work better to get all the project issues without any extra details at first and only get the comments if the task was opened or if the refresh event is being fired. I already made it do that but I need to add a recursive like behavior to get all the project issues and not only the latest 100.

## Issues Resolved

#564 is now fixed
#562 is partially fixed, But should not be closed yet as I am going to make more optimizations for it by the end of the next weekend.

## Check List

- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Comment by johannesjo** [comment]
Thank you very much! Looks good to me! 

Another way to avoid having to deal with the rate limit might be using a bulk request via a `refreshIssues()` (plural) function on the issue service and the different Issue services and use that instead of the forEach. 

I think the gitlab API allows for specifying a list of ids for that:
GET /issues?iids[]=42&iids[]=43
https://docs.gitlab.com/ee/api/issues.html

We can make this an optional interface in IssueServiceInterface to avoid having to deal with Jira and GitHub now (though this might be a nice addition later on).

I don't know. What do you think?

**Comment by MostafaAmin07** [comment]
That's a great idea I will do it today.

**Comment by johannesjo** [comment]
Thank you! I just tested and it seems to work very nicely! 

I assume there is no way, to get the comments in a bulk fashion as well? I did a quick research but didn't find anything...

**Comment by MostafaAmin07** [comment]
Unfortunately, No, At least not that I know of.

Anyway, I will try to make the importing of new issues better in the next few days but it might need some refactoring to the GitLab API service first. I will keep you updated on that.

**Comment by johannesjo** [comment]
That sounds great! Please, let me know if I can help you in any way!

**Pull request merged**
