### PR TITLE
chore: use observable for Formly validation message

### PR DESCRIPTION
**Pull request by aitboudad**
Formly `v5.7` is released and now allows passing validation message as observable which improves live changes when switching language.

### CODE REVIEW

**Comment by johannesjo** [comment]
This is great! Thank you very much!! :)

**Comment by johannesjo** [comment]
Maybe not the right place for this, but I just read on linkedin that you're also working as a freelancer. I am curious: How is the situation for you, if I may ask?

**Comment by aitboudad** [comment]
Seeking for a new challenge (but silently :smile:)

**Comment by johannesjo** [comment]
That sounds good (: Same here in a way.  I wish you good luck with that!

**Comment by aitboudad** [comment]
I get used to it, good luck to you too!

**Pull request merged**
