### PR TITLE
Updated italian translation + added some new translations

### PR DESCRIPTION
**Pull request by loviuz**
# Description

I have updated a lot of italian translations, updating the json file with english one. I also added 2 new placeholder for 2 new translations.

## Issues Resolved

None.

### CODE REVIEW

**Comment by johannesjo** [comment]
Can you have a look at the conflicts?

**Comment by johannesjo** [comment]
Probably it would be the easiest solution to resubmit the changes you have made from the latest master. There are some weird conflicts.

Thank you!

**Comment by loviuz** [comment]
The message above says that this branch has no conflicts. Do I have to resubmit the PR or is it all ok?

**Comment by loviuz** [comment]
Hi @johannesjo, do you prefer that I close this PR and I will re-create a new one with an updated fork?

**Comment by loviuz** [comment]
It seems that only syncing the fork it is now updated. Can you check it?

PS: the error on linting it does not seems to be an error related to the contents of the commit :thinking:

**Comment by johannesjo** [comment]
Thank you very much!

**Pull request merged**
