### PR TITLE
fix: fix date migration error

### PR DESCRIPTION
**Pull request by MostafaAmin07**
This is what I did until now.
I will try to fix the other problems as well.

### CODE REVIEW

**Comment by MostafaAmin07** [comment]
@johannesjo I need your help to understand this.
What does the values in front of each date mean in the project?
```
"workStart": {
        "2019-12-20": 1576851773889,
        "2019-12-27": 1577444198339,
        "٢٠١٩-١٢-٢٧": 1577445050846,
        }
```

**Comment by johannesjo** [comment]
Very clean code! I like it! Thank you very much. We might also have to pre

**Comment by johannesjo** [comment]
Very clean code! I like it! Thank you very much! 

Not sure if we'd also need to do this for chinese, japanese and korean numbers. Probably yes, I'll try to implement this next week.

**Comment by MostafaAmin07** [comment]
Thank you <3.
I don't think these languages will cause any problem as moment returns the date with Western-Arabic numerals for them.
There are 2 languages that could have caused problems but they are not currently supported in the app (Hindi - Persian) and after the fix, I don't think they will.

**Comment by johannesjo** [comment]
@MostafaAmin07 oh cool. Thanks for investigating (or kudos for knowing these kind of things).

**Pull request merged**
