### PR TITLE
Create dependabot.yml

### PR DESCRIPTION
**Pull request by cwerner1**
# Description

Automated Dependecy management by dependabot.
dependabot will automatcly create a new Pull Request, when an dependency is updated. Also the changes are tested with the github actions.

## Issues Resolved

-

### CODE REVIEW

**Comment by johannesjo** [comment]
Thanks for creating this! I'd imagine that this might be quite annoying :D It also wonder how it's supposed to work with breaking changes. But let's give it a shot.

**Comment by cwerner1** [comment]
If it get too annoying, you could set the timer to monthly, to reduce the noise. 

The code snippet is:
`update_schedule:` "monthly"`

greetings from austria

**Comment by cwerner1** [comment]
@johannesjo 
I also would suggest, that you could select "rebase and merge" at the pull request, from Dependabot, to reduce the branches in the git commit history
grafik

**Comment by johannesjo** [comment]
Ahh. Thank you very much for the advice. I am already pretty annoyed, but the feeling of being more and more up to date is also kind of addictive :D I probably should make a single commit updating everything once.

**Pull request merged**
