### PR TITLE
Fix handling of WebDAV headers

### LINKED ISSUE #1199: WebDAV sync always claims a remote conflict with some WebDAV servers (nginx)
### Your Environment

* Version used: 3f321c18fcbc16267bbc23c3b7dcdee37daa2952
* Operating System and version: Linux 5.11.16-2-MANJARO #1 SMP PREEMPT Thu Apr 22 09:53:11 UTC 2021 x86_64 GNU/Linux

* Desktop Environment:  KDE

### Expected Behavior
WebDAV sync should work with WebDAV-compliant servers.

### Current Behavior
WebDAV sync fails with nginx, as the conflict resolution relies on the `etag` header being returned from `PROPFIND` (through getStat in the webdav client), but this header is not returned from `PROPFIND` at least on nginx. (This seems to be consistent with the WebDAV spec http://www.webdav.org/specs/rfc4918.html#rfc.section.9.1.3)

### Steps to Reproduce (for bugs)

1. Setup sync with a nginx webdav server
2. Wait
3. On any upload after an initial upload, the user is warned that the remote has been modified, although it hasn't been, and asked to resolve the conflict. The last sync date will by the 0 unix timestamp.

### Possible fix
I think one fix is to issue a `HEAD` request instead, which is both faster and should return a header with `etag`. I'll try to add this support to the webdav-client and test a fix.

### PR DESCRIPTION
**Pull request by wilbowma**
# Description

This fixes issues with the handling of WebDAV headers:
- Don't attempt to set Content-Length manually (as browsers forbid this and set it automatically; Axios does the right thing, apparently)
- Correct handling of ETAG header, which is not always present in PUT or PROPFIND requests.

## Issues Resolved

 #1199 and #1197

## Check List

- [ ] New functionality includes testing.
- [X] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Comment by wilbowma** [comment]
#1150 may also be related

**Comment by johannesjo** [comment]
Thank you very much! I just checked with the most recent version of the webdav package which includes typing for the web client and there seem to be other inconsistencies as well. Would you mind having a look at them, too?

**Comment by wilbowma** [comment]
Ah, I was just playing with build options and was getting new errors... that must be why. I'll take a closer look tomorrow.

**Comment by johannesjo** [comment]
Thank you! Please, let me know if I can assist you in any way!

**Comment by johannesjo** [comment]
@wilbowma In case your busy, I can also have a look. Would be nice to merge to merge your fix for the next release, which planned for next Monday. :)

**Comment by wilbowma** [comment]
Go ahead; I haven’t started as the CORS issue ate up a bunch of my time.

--

**Pull request merged**
