### PR TITLE
Adding "Assigned to me " filter in github settings

### PR DESCRIPTION
**Pull request by LordJABA**
# Description

Adds additional toggle to github project settings. When chcecked it will only fetch actions assigned to username provided in options

- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Comment by johannesjo** [comment]
Love it! Could you check the conflicts please?

**Comment by LordJABA** [comment]
Glad you like it. Makes it usable with bigger shared projects. 
If we can trust git - no conflicts, should be ready to merge. If I'm messing something up: sorry - first public pull outside work projects.

**Comment by johannesjo** [comment]
I am getting a "This branch cannot be rebased due to conflicts"

Could you merge the current master branch into your project once more?

Otherwise I can also do it. No problem! But I thought since this is your first PR you might want to give it a shot yourself :)

**Comment by LordJABA** [comment]
Resynced fork. 
image
will close this and open new pull

**Pull request closed without merging**
