### PR TITLE
Implement Redmine as issue provider

### PR DESCRIPTION
**Pull request by stealthyV1per**
# Description

Implementing Redmine as issue provider by utilizing their [REST API](https://www.redmine.org/projects/redmine/wiki/Rest_api).
I've already tested it multiple times (local and in a production environment) and it worked great.
*Tho to be fair, for the `localhost:4200` variant to work, you have to install a CORS extension and use the parameters key method for authentication.*

Context: This is my first time working with TypeScript and Angular, and I had to look at some of the other implementations for reference.

## Issues Resolved

- https://github.com/johannesjo/super-productivity/issues/24
- https://github.com/johannesjo/super-productivity/issues/755

*Both are resolved (due to inactivity) but are related*

## Check List

- [x] New functionality includes testing.
- [ ] ~~New functionality has been documented in the README if applicable.~~

### CODE REVIEW

**Comment by stealthyV1per** [comment]
I've seen that you pushed a new release this day. So I have to ask, when can I expect this to go live?

**Comment by johannesjo** [comment]
Hey there! Thanks a lot! Not sure what is up with the package-lock.json to be honest, but maybe we need to remove it from the PR for the build tasks to run.

I can make another release shortly after the feature is merged if there are no unexpected issues with it. Just let me know what suits you :)

**Comment by stealthyV1per** [comment]
I've tested this against a local Redmine container and a productive Redmine instance. IMO this feature can go live, but more testing is welcome.

**Comment by stealthyV1per** [comment]
> Not sure what is up with the package-lock.json to be honest, but maybe we need to remove it from the PR for the build tasks to run.

I'll try to fix this later today. Perhaps deleting was not correct but to discard the changes I've made.

**Comment by johannesjo** [comment]
Thank you very much! I try to make a new release this Friday.

**Pull request merged**
