### PR TITLE
Fixes issues with #164

### PR DESCRIPTION
**Pull request by theCalcaholic**
Sorry for the trouble. This should fix it.

### CODE REVIEW

**Comment by johannesjo** [comment]
Thank you very much! Will check it out this Friday.

**Comment by johannesjo** [comment]
Looks good now. Thanks again!

**Comment by johannesjo** [comment]
Ah no. Issue still persists. Will have a look myself.

**Comment by johannesjo** [comment]
Ok there is one more minor issue, but I will fix later :)

**Comment by johannesjo** [comment]
After spending more time, I noticed several other calculations for the time spent being wrong.  Sundays are also gone, when clicking on the week export button. Might be good case for some unit testing.

Will have another look after lunch, but I don't know how much I will get done today.

**Comment by johannesjo** [comment]
Screenshot from 2019-04-26 14-28-58
Screenshot from 2019-04-26 14-30-39
Screenshot from 2019-04-26 14-30-50
Screenshot from 2019-04-26 14-30-57
Screenshot from 2019-04-26 14-31-10

**Comment by theCalcaholic** [comment]
Hey, sorry to get back to this so late - could you elaborate what is calculated/displayed wrong in each screenshot?
I have a hard time finding the errors :)

**Comment by johannesjo** [comment]
If you compare the time spent of the tasks you'll find that they don't match up, and they also don't match up with the total time spent for a given day. For example the total time spent for the 23rd should be 17minutes but on the second screenshot you see only 10m.

**Pull request merged**
