### PR TITLE
Zh-CN translation finished!

### PR DESCRIPTION
**Pull request by PannenetsF**
#451  and fix all 'GithHub' typo

### CODE REVIEW

**Comment by johannesjo** [comment]
Wow! Thank you so much! This is amazing and must have been a lot of work.

**Comment by johannesjo** [comment]
The changes will be available with the next release btw.

**Comment by PannenetsF** [comment]
> The changes will be available with the next release btw.

Oops, I just found I did not follow the 'feat: ' pattern...

**Comment by johannesjo** [comment]
No worries :)

**Pull request merged**
