### PR TITLE
feat: add transition handling to openproject

### LINKED ISSUE #2005: Add jira transition handling to openproject integrations
## Problem Statement
I really want that on openproject, would be so helpful.
Add Jira transition handling to openproject integration.

## :grey_question: Possible Solution
When transitioning  between Play/Pause/Done have a option to change issue status on openproject, just like jira does.

## :heavy_plus_sign: Additional context

I think i can try to get it done

WDYT @johannesjo

### PR DESCRIPTION
**Pull request by hugaleno**
# Description

Add transition handling for openproject integration with number #2005 
Add Start and Done transitions, pause transition not supported yet, need some changes on action unsetCurrentTask to add task id.

I think is ready for you to review @johannesjo 

let me know if you want to change something.

## Issues Resolved

#2005 

## Check List

- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Comment by johannesjo** [comment]
Hey there! Could you possibly check the linting errors? Thank you! :)

**Comment by hugaleno** [comment]
Lintin is ok.
image

It's complaining about an error on "No provider for store" when creating OpenProjectApiService

image

Do you have any hints for what is causing this problem and how to solve it? I just injected the service on OpenprojectCfgComponent

**Comment by johannesjo** [comment]
Ah alright, sorry. I thought we're dealing with linting errors, but actually it's the unit tests. As There are no sensible unit tests fro the OpenProjectCfgComponent you can just delete or comment out the whole `openproject-cfg.component.spec.ts`.

**Comment by hugaleno** [comment]
Now it passed, need anything else?

**Comment by johannesjo** [comment]
Thank you very much @hugaleno ! The code looks very clean! I like it :)

I've just tested with a brand new open project instance and I get 403 for 
`http://localhost:8080//api/v3/time_entries/form`

`{"_type":"Error","errorIdentifier":"urn:openproject-org:api:v3:errors:MissingPermission","message":"You are not authorized to access this resource."}`

Is this expected?

**Comment by johannesjo** [comment]
Thank you very much @hugaleno ! The code looks very clean! I like it :) Seems to work nicely, though I have to admit that I haven't tested it extensively. I'll merge this for now, so people can test this via the snap edge channel.

**Comment by hugaleno** [comment]
All right. If someone report anything related to this let me know

**Pull request merged**
