### PR TITLE
Android translate ru

### PR DESCRIPTION
**Pull request by nonameformr**
# Description

Describe what this change achieves

## Issues Resolved

List any existing issues this PR resolves

## Check List

- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Comment by johannesjo** [comment]
There seem to be some conflicts. Can you maybe have a look?

**Comment by nonameformr** [comment]
I think I've finished it

**Comment by johannesjo** [comment]
Thank you very much!!!!

**Comment by johannesjo** [comment]
Unfortunately there seem to be some conflicts. Can you have a look?

**Comment by nonameformr** [comment]
i don't understand what happened

**Comment by johannesjo** [comment]
Ah alright. The error has nothing to do with your PR. Sorry! Thank you very much for this!

**Comment by johannesjo** [comment]
No problem! I merged this manually! Thank you very much!

**Pull request merged**
