### PR TITLE
Feature: export grouby option

### PR DESCRIPTION
**Pull request by theCalcaholic**
Implements #162 

super-productivity-group-by-dropdown

This provides a dropdown menu in the worklog export dialog where you can select how the exported rows should be grouped.
The default (and hitherto) behaviour equates to grouping by 'Date'.

### CODE REVIEW

**Comment by theCalcaholic** [comment]
@johannesjo I could not add start/end dates for groupings other than date, because I only have them available regarding dates (i.e. the time when work has been started per day, not per task).

Btw, do any tests need to be implemented/adjusted for this PR?

**Comment by johannesjo** [comment]
Thank you very much. Will check this out tomorrow!

**Comment by johannesjo** [comment]
I just recognized that some of the calculations are off, as they don't match the ones given on the worklog page.
Screenshot from 2019-04-23 15-27-26
Screenshot from 2019-04-23 15-27-52

**Comment by theCalcaholic** [comment]
Hm, not sure what you mean... Did you group by date or by parent task in the second screenshot?

**Comment by theCalcaholic** [comment]
Found the issue. I'm working on it

**Pull request merged**
