### PR TITLE
[WIP] Implement tags for tasks feature

### PR DESCRIPTION
**Pull request by theCalcaholic**
I'm not even remotely done with the feature, but I figured, I'd create the PR anyways (for discussion purposes) :)

Will implement #197 when it's done.

### CODE REVIEW

**Comment by johannesjo** [comment]
Looks good so far 👍 

Let me know if something is ready for a review!

**Comment by theCalcaholic** [comment]
@johannesjo If you want, you could review the overall look and feel of the tag integration into the tasks page. There are still a few minor issues (e.g. the input field should immediately be focused when activated), but the basics are done.

If you don't like the UX concept in general, feel also free to say so.

**Comment by johannesjo** [comment]
Great work! I appreciate it!

I will check the code in a bit. First some feedback on the ui: 

1. For the general look and feel I think the tags from [md-bootstrap](https://mdbootstrap.com/docs/jquery/components/badges/) might be a good inspiration.
2. The UI is much too small I think. Showing a small menu (either as text menu like the project menu or some row of fab-mini icon buttons) on click for the different actions might be better as it would require less precision with the mouse. A menu might contain the following entries for example:
* filter by this tag
* edit tags for this task
* edit this tag (maybe as a modal)
* edit all tags (tag overview)

3. I think there two main scenarios when using tags; a) you quickly want to categorize a task by adding existing ones or new ones and b) you try to adjust your system of tags by fiddling with their names or colors. It might be preferable to have a dialog or separate page for the latter, where you get a quick overview on all that is there. For case a) I think the most efficient way for a user to add them, would be using the short syntax when creating the task (e.g. `#myTag`) while ideally providing autocompletion and also maybe making them editable this way even after a task was created. Second most efficient might be a dedicated auto completion input like the chip-list-input component we could show using the task menu or via a keyboard shortcut. Here a button to quickly delete an added tag would be useful.
4. I think we don't really need the tag icon. It's not providing any additional information. Before checking the material icons page, I didn't even know that this icon stands for tags :)
5. Not sure on this, but the default background could be one of the material palette.

**Comment by theCalcaholic** [comment]
Don't worry, I'm not frustrated. I just hadn't time to consider respond yet (because of vacation among other things :wink: )
I'll get back to it soon.

**Comment by theCalcaholic** [comment]
@johannesjo I'm sorry for the long period of silence on my end.
Unfortunately I have to acknowledge that I'm facing more than just a bit of stress and can't guarantee that I'll be able to continue this work anytime soon.

If it is helpful, you can of course make use of what I've accomplished so far, but don't feel pressed to do so.

**Comment by johannesjo** [comment]
@theCalcaholic no worries! Thank you very much for your effort and getting back to me. It's quite a lot that you accomplished already and I really appreciate the effort! 

Currently I am working on restructuring the database. Once that is done I will definitely revisit this.

**Comment by johannesjo** [comment]
Thank you very much again. The code you provided was a very good basis to make this happen.

**Comment by theCalcaholic** [comment]
Awesome. I love the new tags :)

**Pull request merged**
