### PR TITLE
[WIP] Polish translation

### PR DESCRIPTION
**Pull request by JustAPhrog**
Polish translation

# Description

Translation of app to polish language.

## Issues Resolved

None.

## Check List

- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Comment by johannesjo** [comment]
Thank you very much!

**Comment by johannesjo** [comment]
Is this ready for merge? I ask because you marked the PR as work in progress.

**Comment by JustAPhrog** [comment]
@johannesjo It's still WIP. Lots of translation still missing.

**Comment by johannesjo** [comment]
Hello @JustAPhrog ! I hope it's ok if I merge this WIP.

**Comment by JustAPhrog** [comment]
Sorry, I couldn't find time to finish this. I'm glad that someone finished this.

**Pull request merged**
